# =========================
# order-db PVC
# =========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# =========================
# order-db Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          image: postgres:15
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              value: order
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-db-pvc
      volumes:
        - name: order-db-pvc
          persistentVolumeClaim:
            claimName: order-db-pvc

---
# =========================
# order-db Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
# =========================
# order-service Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: default-route-openshift-image-registry.apps.rm3.7wse.p1.openshiftapps.com/hoarah-loux-dev/order-service:v100
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://order:password@order-db:5432/orderdb
            - name: POSTGRES_URI
              value: postgresql+asyncpg://order:password@order-db:5432/orderdb
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: RABBITMQ_EXCHANGE
              value: "users"
          readinessProbe:
            httpGet:
              path: /api/v1/orders/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

---
# =========================
# order-service Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
